# AIYA Matrix服务器配置模板 (修复版)
# 此文件为Docker Compose部署提供参考配置

## Matrix服务器名称 - 不能在部署后更改
serverName: DOMAIN_PLACEHOLDER

## 全局标签
labels:
  environment: "production"
  deployment: "docker-compose"

## 全局配置
global:
  domain: DOMAIN_PLACEHOLDER
  certEmail: CERT_EMAIL_PLACEHOLDER
  certMode: CERT_MODE_PLACEHOLDER

## Synapse (Matrix服务器核心)
synapse:
  enabled: true

  # 服务器配置
  config:
    serverName: DOMAIN_PLACEHOLDER
    publicBaseurl: "https://DOMAIN_PLACEHOLDER"

    # 数据库配置
    database:
      name: "synapse"
      user: "synapse"
      password: "POSTGRES_PASSWORD_PLACEHOLDER"
      host: "postgres"
      port: 5432

    # 媒体存储配置
    media:
      maxUploadSize: "100M"
      maxImagePixels: "32M"

    # 注册配置
    registration:
      enabled: true
      requiresToken: false
      allowGuests: false

    # 联邦配置
    federation:
      enabled: true

    # 日志配置
    logging:
      level: "INFO"

  # 资源配置 (适配小型环境)
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  # 持久化存储
  persistence:
    enabled: true
    size: "50Gi"

## Element Web (Web客户端)
elementWeb:
  enabled: true

  # 配置
  config:
    defaultServerName: DOMAIN_PLACEHOLDER
    defaultServerUrl: "https://DOMAIN_PLACEHOLDER"
    brand: "Element"

    # 功能配置
    features:
      voip: true
      widgets: true
      communities: true
      threads: true

## PostgreSQL数据库
postgres:
  enabled: true

  # 数据库配置
  auth:
    database: "synapse"
    username: "synapse"
    password: "POSTGRES_PASSWORD_PLACEHOLDER"

  # 持久化存储
  persistence:
    enabled: true
    size: "20Gi"

  # 资源配置
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

## Nginx反向代理
nginx:
  enabled: true

  # 配置
  config:
    domain: DOMAIN_PLACEHOLDER
    sslCertPath: "/etc/letsencrypt/live/DOMAIN_PLACEHOLDER"

  # 安全配置
  security:
    enableHSTS: true
    enableCSP: true
    maxBodySize: "100M"

## SSL证书配置
ssl:
  enabled: true
  provider: "letsencrypt"
  mode: CERT_MODE_PLACEHOLDER
  email: CERT_EMAIL_PLACEHOLDER
  domains:
    - DOMAIN_PLACEHOLDER
    - "element.DOMAIN_PLACEHOLDER"

## 全局安全配置
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

## 监控配置
monitoring:
  enabled: false  # 可选启用

## 备份配置
backup:
  enabled: false  # 可选启用

## 网络配置
network:
  type: "bridge"
  name: "matrix_network"

## 端口配置
ports:
  http: 80
  https: 443
  synapse: 8008
  federation: 8448
  element: 8080