# Element Server Suite 内网部署配置模板
# 此文件将根据用户配置自动生成

## Matrix服务器名称 - 不能在部署后更改
serverName: DOMAIN_PLACEHOLDER

## 全局标签
labels:
  environment: "production"
  deployment: "internal"

## 全局Ingress配置
ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  className: "nginx"
  tlsEnabled: true

## 证书管理器配置
certManager:
  clusterIssuer: CERT_ISSUER_PLACEHOLDER

## Synapse (Matrix服务器核心)
synapse:
  enabled: true
  
  # 服务器配置
  config:
    serverName: DOMAIN_PLACEHOLDER
    publicBaseurl: "https://DOMAIN_PLACEHOLDER:HTTPS_PORT_PLACEHOLDER"
    
    # 数据库配置
    database:
      name: "synapse"
      user: "synapse"
      host: "postgres"
      port: 5432
    
    # 媒体存储配置
    media:
      maxUploadSize: "100M"
      maxImagePixels: "32M"
    
    # 注册配置
    registration:
      enabled: true
      requiresToken: false
      allowGuests: false
    
    # 联邦配置
    federation:
      enabled: true
      port: FEDERATION_PORT_PLACEHOLDER
    
    # 日志配置
    logging:
      level: "INFO"
  
  # Ingress配置
  ingress:
    host: DOMAIN_PLACEHOLDER
    annotations:
      cert-manager.io/cluster-issuer: CERT_ISSUER_PLACEHOLDER
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    tls:
      - hosts:
          - DOMAIN_PLACEHOLDER
        secretName: synapse-tls
  
  # 服务配置
  service:
    type: NodePort
    ports:
      http:
        port: 8008
        nodePort: INTERNAL_HTTP_PORT_PLACEHOLDER
      federation:
        port: 8448
        nodePort: FEDERATION_PORT_PLACEHOLDER
  
  # 资源配置 (适配50人会议)
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  
  # 持久化存储
  persistence:
    enabled: true
    storageClass: ""
    size: "50Gi"
    mountPath: "DEPLOY_DIR_PLACEHOLDER/synapse/data"

## Element Web (Web客户端)
elementWeb:
  enabled: true
  
  # 配置
  config:
    defaultServerName: DOMAIN_PLACEHOLDER
    defaultServerUrl: "https://DOMAIN_PLACEHOLDER:HTTPS_PORT_PLACEHOLDER"
    brand: "Element"
    
    # 功能配置
    features:
      voip: true
      widgets: true
      communities: true
      threads: true
  
  # Ingress配置
  ingress:
    host: "element.DOMAIN_PLACEHOLDER"
    annotations:
      cert-manager.io/cluster-issuer: CERT_ISSUER_PLACEHOLDER
    tls:
      - hosts:
          - "element.DOMAIN_PLACEHOLDER"
        secretName: element-web-tls
  
  # 服务配置
  service:
    type: NodePort
    port: 80
    nodePort: INTERNAL_HTTPS_PORT_PLACEHOLDER

## Element Call (视频会议)
elementCall:
  enabled: true
  
  # 配置
  config:
    defaultServerName: DOMAIN_PLACEHOLDER
    defaultServerUrl: "https://DOMAIN_PLACEHOLDER:HTTPS_PORT_PLACEHOLDER"
    
    # 媒体配置 (适配50人会议)
    media:
      maxParticipants: 50
      enableScreenShare: true
      enableRecording: false
  
  # Ingress配置
  ingress:
    host: "call.DOMAIN_PLACEHOLDER"
    annotations:
      cert-manager.io/cluster-issuer: CERT_ISSUER_PLACEHOLDER
    tls:
      - hosts:
          - "call.DOMAIN_PLACEHOLDER"
        secretName: element-call-tls
  
  # 资源配置
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

## Matrix RTC (实时通信)
matrixRtc:
  enabled: true
  
  # 配置
  config:
    # TURN服务器配置
    turn:
      enabled: true
      realm: DOMAIN_PLACEHOLDER
      
    # UDP端口范围
    udpPortRange:
      min: UDP_PORT_START_PLACEHOLDER
      max: UDP_PORT_END_PLACEHOLDER
  
  # 服务配置
  service:
    type: NodePort
    udpPortRange:
      start: UDP_PORT_START_PLACEHOLDER
      end: UDP_PORT_END_PLACEHOLDER

## PostgreSQL数据库
postgres:
  enabled: true
  
  # 数据库配置
  auth:
    database: "synapse"
    username: "synapse"
    password: "POSTGRES_PASSWORD_PLACEHOLDER"
  
  # 持久化存储
  persistence:
    enabled: true
    size: "20Gi"
    mountPath: "DEPLOY_DIR_PLACEHOLDER/postgres/data"
  
  # 资源配置
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

## HAProxy (负载均衡)
haproxy:
  enabled: true
  
  # 配置
  config:
    # 后端服务器配置
    backends:
      synapse:
        servers:
          - "synapse:8008"
      element-web:
        servers:
          - "element-web:80"
      element-call:
        servers:
          - "element-call:80"
  
  # 服务配置
  service:
    type: NodePort
    ports:
      http:
        port: 80
        nodePort: INTERNAL_HTTP_PORT_PLACEHOLDER
      https:
        port: 443
        nodePort: INTERNAL_HTTPS_PORT_PLACEHOLDER

## Matrix Authentication Service (可选)
matrixAuthenticationService:
  enabled: false  # 默认使用Synapse内置认证

## 全局持久化配置
persistence:
  storageClass: ""
  accessMode: "ReadWriteOnce"
  
## 全局安全配置
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

## 网络策略
networkPolicy:
  enabled: false  # 内网环境可以禁用

## 监控配置
monitoring:
  enabled: false  # 可选启用

## 备份配置
backup:
  enabled: false  # 可选启用